import {
  Alarm,
  AppleLogo,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Bell,
  BellSimple,
  Bicycle,
  CalendarBlank,
  CalendarCheck,
  CalendarDots,
  Camera,
  Car,
  ChartLineUp,
  ChatCircleDots,
  Check,
  CheckCircle,
  Clock,
  Coffee,
  Compass,
  Crown,
  DotsThree,
  EnvelopeSimple,
  Fire,
  ForkKnife,
  GameController,
  Gift,
  GoogleLogo,
  Heart,
  HeartStraight,
  Hourglass,
  House,
  Images,
  MapPin,
  MapPinArea,
  Megaphone,
  Minus,
  Moon,
  MusicNote,
  NavigationArrow,
  Palette,
  PaperPlaneTilt,
  PathIcon,
  PersonSimpleWalk,
  Phone,
  Plus,
  QrCode,
  ShieldCheck,
  SignOut,
  SlidersHorizontal,
  Smiley,
  Sparkle,
  Star,
  Sun,
  SunDim,
  ThumbsUp,
  Timer,
  Trophy,
  User,
  UserPlus,
  Users,
  UsersThree,
  VideoCamera,
  Wallet,
  X,
} from 'phosphor-react-native';

/** Central icon registry. One family (Phosphor), one source of truth. */
export const iconMap = {
  Alarm,
  AppleLogo,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Bell,
  BellSimple,
  Bicycle,
  CalendarBlank,
  CalendarCheck,
  CalendarDots,
  Camera,
  Car,
  ChartLineUp,
  ChatCircleDots,
  Check,
  CheckCircle,
  Clock,
  Coffee,
  Compass,
  Crown,
  DotsThree,
  EnvelopeSimple,
  Fire,
  ForkKnife,
  GameController,
  Gift,
  GoogleLogo,
  Heart,
  HeartStraight,
  Hourglass,
  House,
  Images,
  MapPin,
  MapPinArea,
  Megaphone,
  Minus,
  Moon,
  MusicNote,
  Navigation: NavigationArrow,
  Palette,
  PaperPlaneTilt,
  Path: PathIcon,
  PersonSimpleWalk: PersonSimpleWalk,
  Phone,
  Plus,
  QrCode,
  ShieldCheck,
  SignOut,
  SlidersHorizontal,
  Smiley,
  Sparkle,
  Star,
  Sun,
  SunDim,
  ThumbsUp,
  Timer,
  Trophy,
  User,
  UserPlus,
  Users,
  UsersThree,
  VideoCamera,
  Walking: PersonSimpleWalk,
  Wallet,
  X,
} as const;

export type PhIconName = keyof typeof iconMap;
export type PhWeight = 'thin' | 'light' | 'regular' | 'bold' | 'fill' | 'duotone';

interface PhProps {
  name: PhIconName;
  size?: number;
  color?: string;
  weight?: PhWeight;
  mirrored?: boolean;
}

/** Icon renderer: name-keyed Phosphor icons. */
export function Ph({ name, ...props }: PhProps) {
  const IconComp = iconMap[name];
  return <IconComp {...props} />;
}
